### PR TITLE
chore: add `.nvmrc` to auto use lts version

### PR DESCRIPTION
**Pull request by kecrily**
## Checklist

* [x] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by kecrily** [comment]
I was having problems with the node latest version. So I switched to the LTS version.

And if someone is using the node version manager, then its package manager will automatically switch to the latest LTS version after `.nvmrc` is added. This takes the hassle out of manually switching versions and keeps the development environment as consistent as possible.

**Comment by t3chguy** [comment]
We don't suggest nvm anywhere, we should instead specify the minimum node version required in the package.json https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines

**Review by t3chguy — APPROVED** [review]
Ultimately I think this does no harm, thanks for your contribution

**Comment by t3chguy** [comment]
We now specify the node version requirement in package.json so this should be no longer necessary

**Pull request closed without merging**
