### PR TITLE
Documentation fix: missing comma and I would also take the ellipsis away

### PR DESCRIPTION
**Pull request by chagai95**
took me a while to find the mistake and "comment" and I think it'll take other even longer...

Signed-off-by: Chagai Friedlander chagai95@gmail.com

### CODE REVIEW

**Comment by t3chguy** [comment]
Your example is still invalid, just in a different way.

> username-colors is expected to contain 8 colors. avatar-background-colors is expected to contain 3 colors. Both values are optional and have fallbacks from the built-in theme.

**Review by turt2live — CHANGES_REQUESTED** [review]
giving the code block a `json5` type and putting inline comments in would be preferred.

**Comment by chagai95** [comment]
Should I open an issue for this then? The code is invalid but it still works, what's are username colors? I'm assuming avatar background colors are the generated profile pictures?

**Comment by t3chguy** [comment]
> what's are username colors?

image

**Comment by chagai95** [comment]
Ah 🤦 thx 😊

**Review by turt2live — APPROVED** [review]

**Comment by richvdh** [comment]
Skipping the CLA requirement since this was written way before the requirement was introduce

**Review by richvdh — APPROVED** [review]

**Pull request merged**
