### PR TITLE
Display an empty pinned message banner when loading

### PR DESCRIPTION
**Pull request by florianduros**
## Checklist

- [ ] Tests written for new code (and old code if feasible).
- [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
- [ ] Linter and other CI checks pass.
- [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

Closes https://github.com/element-hq/element-web/issues/28390

### CODE REVIEW

**Comment by gaelledel** [comment]
tested with netlify build and it is not ideal to have the pinned msg banner empty for so long either. I wonder if we could test to only have the banner with content be displayed once it's ready and fetched? How would this feel like? (need to test)

**Comment by florianduros** [comment]
@gaelledel I don't understand. This is the behaviour on develop/app. We display the banner when the pinned messages are fetched

**Comment by gaelledel** [comment]
After a call with @florianduros. We agreed that it would better to have a blank banner which would in essence be preventing timeline jumpyness in rooms with pinned messages. The timeline jumping up and down as it is currently dramatically impacts the user experience of a core section of our app. I therefore believe keeping this misbehaviour/bug will create negative perception of our product. The impact of keeping this is larger than the fix proposed by Florian. In the future, the timeline rework would ensure we don't have this bug to start with but until then, this PR is an acceptable fix.

**Comment by americanrefugee** [comment]
> After a call with @florianduros. We agreed that it would be better to have a blank banner which would in essence be preventing timeline jumpyness in rooms with pinned messages. The timeline jumping up and down as it is currently dramatically impacts the user experience of a core section of our app. I therefore believe keeping this misbehaviour/bug will create negative perception of our product. The impact of keeping this is larger than the fix proposed by Florian. In the future, the timeline rework would ensure we don't have this bug to start with but until then, this PR is an acceptable fix. Fyi @daniellekirkwood @americanrefugee - please check that you are happy with this.

I'm confused... The intended behavior is that the pinned messages banner displays on top of / over the timeline, not IN the the timeline. I don't understand why the timeline content would be "jumping" up or down.

**Comment by florianduros** [comment]
Replaced by https://github.com/element-hq/element-web/pull/28654

**Pull request closed without merging**
