### PR TITLE
Move state update listeners from constructor to componentDidMount

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/element-hq/element-web/issues/28306

Also ensures `this.unmounted` is set appropriately to account for the React 18 strict mode double-render. Without it your inline definition (`private unmounted = false;`) might only be called once, and you may be unmounted before you are rendered, so none of your data updates end up applying due to `this.unmounted = true` in the unmount before the remount.

### CODE REVIEW

**Review by dbkr — APPROVED** [review]

**Comment by richvdh** [comment]
I'm not really familiar with React's strict mode, so could use some help understanding the changes here. I skimmed https://react.dev/reference/react/StrictMode, but it wasn't that helpful and I could do with some help understanding its specific effects on our application.

For example, why do we need to add `this.unmounted = false;` to `componentDidMount`? This is because the same Component object can now be mounted, unmounted, and re-mounted, I guess?  (Aside: I thought most of the reasons we used the `this.unmounted` flag no longer applied? Did you consider ripping it out rather than propagating it further?)

The PR title is "Move state update listeners from constructor to componentDidMount", but (a) the PR doesn't explain *why* that is a good thing to do; (b) it's not obvious that `this.unmounted = false` counts as a "state update listener".

A few words in the description of the PR might help understand what's going on here.

**Review by richvdh — COMMENTED** [review]
looks sane in general but some clarification would be appreciated

**Comment by t3chguy** [comment]
> This is because the same Component object can now be mounted, unmounted, and re-mounted, I guess?

Indeed, without it your inline definition (`private unmounted = false;`) might only be called once, and you may be unmounted before you are rendered, so none of your data updates end up applying due to `this.unmounted = true` in the unmount before the remount.

> Did you consider ripping it out rather than propagating it further?

I did but thought it much higher risk when in the medium term everything will be getting replaced with functional components which can deal with that.

**Review by richvdh — APPROVED** [review]
lgtm

**Pull request merged**
