### PR TITLE
Fix: 1:1 call - screen sharing no longer works after pressing the cancel button in Element-Desktop

### PR DESCRIPTION
**Pull request by gumara-dev**
Fixes https://github.com/element-hq/element-desktop/issues/1367

Signed-off-by: Stephan Raab <info@gumara.de>

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Review by t3chguy — CHANGES_REQUESTED** [review]
This needs a comment as it is non-obvious, as well as sign-off as per the checklist

> Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md?rgh-link-date=2024-04-08T20%3A19%3A16Z)).

**Comment by gumara-dev** [comment]
> This needs a comment as it is non-obvious, as well as sign-off as per the checklist
> 
> > Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md?rgh-link-date=2024-04-08T20%3A19%3A16Z)).

Signed-off-by: Stephan Raab <info@gumara.de>

**Review by robintown — COMMENTED** [review]
Hi, thanks for the contribution! It's not apparent to me how this fix works. Could you add a comment explaining why we need to always call the callback?

**Comment by gumara-dev** [comment]
> Hi, thanks for the contribution! It's not apparent to me how this fix works. Could you add a comment explaining why we need to always call the callback?

@robintown 

However, the await function that was called by the matrix-js-sdk call.ts on line 1086 never returns. This only happens when a stream is selected.
If this return is now commented out and the this.ipc.call("callDisplayMediaCallback", source); is also executed on cancel, it works.

**Comment by robintown** [comment]
Okay, so in other words the getDisplayMedia promise will never resolve if we don't at least provide a dummy value? That's the kind of thing that should go in a comment in the code.

**Comment by gumara-dev** [comment]
> Okay, so in other words the getDisplayMedia promise will never resolve if we don't at least provide a dummy value? That's the kind of thing that should go in a comment in the code.

That’s correct 👌🏻

**Review by robintown — APPROVED** [review]

**Comment by gumara-dev** [comment]
@robintown Thanks :)

**Pull request merged**
