### PR TITLE
Force Element Call video rooms

### PR DESCRIPTION
**Pull request by toger5**
Video rooms are currently using jitsi. The VoiP team is planning to sunset jitsi in the longer term.
As the first step the video rooms (which are a beta feature that needs to be activated) are using EC instead of jitsi.

This PR activates `feature_element_call_video_rooms` on develop.element.io so that video rooms default to element call instead of jitis.

(existing jitsi video rooms will stay configured with jitsi.)

The PR for Element Desktop: https://github.com/element-hq/element-desktop/pull/1413

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
Should this be applied to Nightly also?

**Comment by toger5** [comment]
Created: https://github.com/element-hq/element-desktop/pull/1413

**Comment by fkwp** [comment]
product approved

**Review by Aziz-4980 — COMMENTED** [review]
LGTM

**Review by andybalaam — APPROVED** [review]

**Comment by toger5** [comment]
The companion PR: https://github.com/element-hq/element-desktop/pull/1413 for element deskop is not yet approved.
Would be great to merge this soonish so the both are behaving similarly.

**Pull request merged**
