### PR TITLE
Update docker nginx config to not force ipv6

### PR DESCRIPTION
**Pull request by yxie2023**
ipv6 support is automatically added via nginx docker's 10-listen-on-ipv6-by-default.sh.

This patch allows element-web to run on system with or without ipv6 enabled.

## Checklist

- [ ] Tests written for new code (and old code if feasible).
- [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
- [ ] Linter and other CI checks pass.
- [x] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

### CODE REVIEW

**Comment by spaetz** [comment]
Vote against from me :-). Sorry, my nginx does not come throough docker and I don't believe disabling IPv6 by default makes sense nowadays. Add a comment to tell people to comment this out if they don't use IPv6, but no one should be just **using** this config without going through it and adapting it as they need fit anyway. Don't just disable IPv6.

**Comment by t3chguy** [comment]
> Vote against from me :-). Sorry, my nginx does not come throough docker and I don't believe disabling IPv6 by default makes sense nowadays. Add a comment to tell people to comment this out if they don't use IPv6, but no one should be just using this config without going through it and adapting it as they need fit anyway. Don't just disable IPv6.

The config isn't intended as an example, but the config we use for our Docker image only. @yxie2023 could you move the `nginx` dir into a `docker` dir to make that clearer, then apply the same change you made therein?

**Comment by yxie2023** [comment]
done @t3chguy. let me know if there's anything else. thank you!

**Review by t3chguy — APPROVED** [review]
Looks sane to me, thanks

**Comment by t3chguy** [comment]
@yxie2023 you would need to sign the CLA if you want your contribution to be merged. Also looks like Sonarcloud won't scan your own `develop` branch so you'd need to contribute from a different branch name.

**Comment by yxie2023** [comment]
I signed the CLA. 

Resubmitting from "contrib" branch: https://github.com/element-hq/element-web/pull/28771

**Pull request closed without merging**
