### PR TITLE
Update welcome page buttons styling from square to rounded

### PR DESCRIPTION
**Pull request by shivamb11**
Fixes: #27468 

Changed buttons styling and added hover effect on them for improved user experience.

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md)).

Before:
Screenshot 2024-05-15 195228

After:
Screenshot 2024-05-15 195205

### CODE REVIEW

**Comment by florianduros** [comment]
Thanks for you contribution.
The changes are design related, we will wait for the opinion design team on it.

**Comment by shivamb11** [comment]
Sure thing. Glad to have worked on it.

**Comment by Hinaichigo** [comment]
Rounded doesn't mean necessarily better user experience. Round buttons and elements can be aesthetically distracting.

**Comment by MidhunSureshR** [comment]
Closing this since it's not really enough that the buttons are rounded, they also need to match thematically with the rest of the application. The Design team will tackle this soon.

**Pull request closed without merging**
