### PR TITLE
Add the Intl API to the modermizr checks

### PR DESCRIPTION
**Pull request by dbkr**
Also change to to not minify, because it will be minified by webpack anyway so we may as wel have a halfway sensible diff next time.

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
Looking at https://github.com/Modernizr/Modernizr/blob/master/feature-detects/intl.js#L19-L21 I'm not sure this adds anything over our existing `Intl.Segmenter` check https://github.com/element-hq/element-web/blob/develop/src/vector/index.ts#L77-L78

**Comment by dbkr** [comment]
Oh I see, we should probably just remove that now there's a built in one?

**Comment by t3chguy** [comment]
@dbkr look at the link I sent. It just checks for `window.Intl` existing. It'd pass on FF ESR115, whereas the one I wrote would correctly fail, as FF ESR115 lacks Intl.Segmenter. The various Intl APIs came in at different times. The built-in Modernizr rule seems too basic to actually be useful.

**Comment by dbkr** [comment]
oh right, I see. In that case I'll add that as a comment as that's deeply unintuitive.

**Pull request closed without merging**
