### PR TITLE
Fix 'remove alias' button in room settings

### PR DESCRIPTION
**Pull request by Dev-Gurjar**
## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [x] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web).

## Before and After Comparison:

<table>
  <tr>
    <td><strong>Before:</strong></td>
    <td><strong>After:</strong></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

## Explanation:

The size of the button had to be increased to prevent the "close room settings" button from breaking. The images above show the difference before and after the changes, with the button's size adjustment ensuring proper functionality and alignment.

### CODE REVIEW

**Comment by Dev-Gurjar** [comment]
this is my first open source contribution please tell me what am i doing wrong?

**Review by florianduros — CHANGES_REQUESTED** [review]
Hi! Thanks for your contribution!

As you can see in the result of the e2e test (e2e-28269--matrix-react-sdk.netlify.app), the css changes introduce a regression on the dialog close button.

**Comment by florianduros** [comment]
@Dev-Gurjar 

Click on *View deployment* of the e2e test line.
image

or

The check mark is green in the CI check
image

**Comment by Dev-Gurjar** [comment]
is it working now?

**Review by florianduros — APPROVED** [review]
Tested and working! Thanks for the contribution.

**Pull request merged**
